@PeresentationLayer_HostAddress = http://localhost:5289

GET {{PeresentationLayer_HostAddress}}/api/Products

###

GET {{PeresentationLayer_HostAddress}}/api/Products/brands

###

GET {{PeresentationLayer_HostAddress}}/api/Products/types

###

@id=1
GET {{PeresentationLayer_HostAddress}}/api/Products/{{id}}

###
